@startuml ClassModel
class Mastermind {
    -askYesOrNo()
    +play()
}
class Game{
    -MAX_ATTEMPS
    -proposedCombinations
    -playerMove()
    -askPlayerCombination()
    -addProposedCombination()
    -showAllProposedCombinations()
    -isOver()
    -getGameOverMsg()
    +play()
}
abstract Combination{
    -COLOR_OPTIONS
    -MAX_COLORS
    +get()
    +set()
}
class SecretCombination{
    -getNewRandomColor()
    +generate()
}
class PlayerCombination{
    -hasRepeatedColor()
    -areColorsInOptions()
    +getError()
}
class Result{
    -blacks
    -whites
    +getBlacks()
    +getWhites()
    +isWinner()
    +set()
}
class ColorChecker{
    +isColorInArray()
}
Mastermind o-- Game
Game *-- SecretCombination
Game *-- PlayerCombination
Game *-- Result
Combination <|-- SecretCombination
Combination <|-- PlayerCombination
Result ..> ColorChecker
PlayerCombination ..> ColorChecker
@enduml
